version: 2
jobs:
  build:
    docker:
      # Because it has gradle
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - run:
          name: Build and test
          command: ./gradlew --info test
      - store_artifacts:
          path: build/reports/tests
          destination: tests
